name: Build and Package Jar

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project and package Jar
        run: mvn -B clean package --file project-slt-groupG/pom.xml

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tic-tac-toe-jar
          path: project-slt-groupG/target/*.jar